@entryPoint = http://localhost:4100/api/v1
# @entryPoint = http://learnerr-api-dev.herokuapp.com/api/v1
@accessToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMywidXNlcm5hbWUiOiJZdW1lZG8iLCJ0aXRsZSI6bnVsbCwicHJvZmlsZV9waWNfdXJsIjpudWxsLCJpc0FjdGl2ZSI6dHJ1ZSwicm9sZSI6InVzZXIifSwiaWF0IjoxNjU5NTI2OTMwLCJleHAiOjE2NTk1Mjc4MzB9.xZRrh9jHZPD7vajhZL3V6-AiXD_dXQXcIGSbFAgO1EI

@refreshToken = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwidXNlcm5hbWUiOiJZdW1lZG8iLCJ0aXRsZSI6bnVsbCwicHJvZmlsZV9waWNfdXJsIjpudWxsLCJpc0FjdGl2ZSI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY1OTM3NzQ2MiwiZXhwIjoxNjU5MzgxMDYyfQ.FN5S9Ym-hSiRz26g3mcrysZTfbAAL1WYgwvnsvZQZWM



#& -----------------------------------------------
#~ ------------------------------------------ USER
#& -----------------------------------------------


#^ ------------------------ fetchAllUsers
###
GET {{entryPoint}}/users
Content-Type: application/json


#^ ------------------------ fetchOneUser
###
GET {{entryPoint}}/users/5
Content-Type: application/json
{{accessToken}}


#^ ------------------------ updateUser
###
PATCH {{entryPoint}}/users/11
Content-Type: application/json
{{accessToken}}

{
    "username": "Yumedo",
    "profile_pic_url":"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg",
    "linkedin_url":"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/745.jpg"
}


#^ ------------------------ deleteUser
###
DELETE {{entryPoint}}/users/13
Content-Type: application/json
{{accessToken}}


#^ ------------------------ inactivateUser
###
PUT {{entryPoint}}/users/1
Content-Type: application/json
{{accessToken}}

{
    "is_active": true
}


# --------------------------------------- SIGNUP
#~ ------------------------ doSignUp
###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "username": "Yumedo",
    "email": "yumedo9@survivor.com",
    "password": "N6y$Ozddzt=1aa",
    "passwordConfirm": "N6y$Ozddzt=1aa"
}


# --------------------------------------- SIGNIN
#~ ------------------------ doSignIn
###
POST {{entryPoint}}/signin
Content-Type: application/json

{
  "email": "yumedo9@survivor.com",
  "password": "N6y$Ozddzt=1aa"
}


# --------------------------------------- SIGNOUT
#~ ------------------------ doSignOut
###
GET {{entryPoint}}/signout
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ fetchPanelUser
###
GET {{entryPoint}}/users/1/panel
Content-Type: application/json
{{accessToken}}


#^ ------------------------ refreshToken
###
POST {{entryPoint}}/refreshtoken
Content-Type: application/json
{{refreshToken}}



#& -----------------------------------------------
#~ --------------------------------------- ARTICLE
#& -----------------------------------------------

#^ ------ createArticle
###
POST {{entryPoint}}/articles
Content-Type: application/json
{{accessToken}}

{
    "title": "NodeJS et Express V2",
    "abstract": "Une API comme jamais",
    "content": "Ea exercitationem at aut velit odio aut. Autem architecto corrupti adipisci praesentium harum quia. Vel reprehenderit asperiores consequatur. Magnam non eaque. Laboriosam itaque vitae",
    "user_id":12,
    "status_id":1
}


#^ ------ fetchAllArticles
###
GET {{entryPoint}}/articles
Content-Type: application/json


#^ ------ fetchOneArticle
###
GET {{entryPoint}}/articles/2
Content-Type: application/json


#^ ------ updateArticle
###
PATCH {{entryPoint}}/articles/19
Content-Type: application/json
{{accessToken}}

{
    "title": "BBBBBB",
    "abstract": "Une API comme jamais",
    "content": "Ea exercitationem at aut velit odio aut. Autem architecto corrupti adipisci praesentium harum quia. Vel reprehenderit asperiores consequatur. Magnam non eaque. Laboriosam itaque vitae",
    "user_id":100,
    "status_id":1
}

#^ ------ deleteArticle
###
DELETE {{entryPoint}}/articles/18
Content-Type: application/json
{{accessToken}}


#^ ------ fetchAllArticlesByCategory
###
GET {{entryPoint}}/categories/1/articles
Content-Type: application/json


#^ ------ fetchAllArticlesByUser
###
GET {{entryPoint}}/users/9/articles
Content-Type: application/json


#^ ------ fetchLastestArticles
###
POST {{entryPoint}}/articles/last
Content-Type: application/json

{
    "limitNb":2,
    "offsetNb":0
}

#^ ------ searchAllArticles
###
POST {{entryPoint}}/articles/search
Content-Type: application/json

{
    "search":"rem"
}



#& -----------------------------------------------
#~ ---------------------------------- ERROR-TICKET
#& -----------------------------------------------

#^ ------ createErrorTicket
###
POST {{entryPoint}}/errors
Content-Type: application/json
{{accessToken}}

{
    "error_snippet":"FAILED--Further testing stopped: Cannot continue: connection failed",
    "title": "T_T",
    "abstract": "T_T",
    "content": "T_T",
    "user_id":50,
    "status_id":"1"
}


#^ ------ fetchAllErrorTickets
###
GET {{entryPoint}}/errors
Content-Type: application/json


#^ ------ fetchOneErrorTicket
###
GET {{entryPoint}}/errors/12
Content-Type: application/json


#^ ------ updateErrorTicket
###
PATCH {{entryPoint}}/errors/12
Content-Type: application/json
{{accessToken}}

{
    "error_snippet":"FAILED--Further testing stopped: Cannot continue: connection failed",
    "title": "HELP ME 2",
    "abstract": "T_T",
    "content": "T_T",
    "user_id":12,
    "status_id":"1"
}


#^ ------ updateErrorTicketSolution
###
PATCH {{entryPoint}}/errors/12/solution/11
Content-Type: application/json
{{accessToken}}

{
    "error_comment_id":1,
    "user_id":12
}


#^ ------ deleteErrorTicket
###
DELETE {{entryPoint}}/errors/12
Content-Type: application/json
{{accessToken}}


#^ ------ fetchAllErrorTicketsByCategory
###
GET {{entryPoint}}/categories/1/errors
Content-Type: application/json


#^ ------ fetchAllErrorTicketsByUser
###
GET {{entryPoint}}/users/1/errors
Content-Type: application/json


#^ ------ fetchLastestErrorTickets
###
POST {{entryPoint}}/errors/last
Content-Type: application/json

{
    "limitNb":2,
    "offsetNb":0
}


#^ ------ searchAllErrorTickets
###
POST {{entryPoint}}/errors/search
Content-Type: application/json

{
    "search":"sint"
}



#& -----------------------------------------------
#~ ------------------------------- ARTICLE-COMMENT
#& -----------------------------------------------

#^ ------ createArticleComment
###
POST {{entryPoint}}/articles/10/comments
Content-Type: application/json
{{accessToken}}

{
    "content": "Ceci est un commentaire o_O",
    "user_id":12
}


#^ ------ fetchAllArticleComments
###
GET {{entryPoint}}/articles/3/comments
Content-Type: application/json


#^ ------ updateArticleComment
###
PATCH {{entryPoint}}/articles/10/comments/12
Content-Type: application/json
{{accessToken}}

{
    "content":"Hello c'est une modif",
    "user_id":5
}


#^ ------ deleteArticleComment
###
DELETE {{entryPoint}}/articles/10/comments/11
Content-Type: application/json
{{accessToken}}

{
    "user_id":5
}


#^ ------ fetchAllArticleCommentsByUser
###
GET {{entryPoint}}/users/1/article_comments
Content-Type: application/json
{{accessToken}}





#& -----------------------------------------------
#~ --------------------------------- ERROR-COMMENT
#& -----------------------------------------------

#^ ------ createErrorComment
###
POST {{entryPoint}}/errors/10/comments
Content-Type: application/json
{{accessToken}}

{
    "content": "Ceci est un commentaire d'une erreur o_O",
    "user_id":5
}


#^ ------ fetchAllErrorComments
###
GET {{entryPoint}}/errors/1/comments
Content-Type: application/json


#^ ------ updateErrorComment
###
PATCH {{entryPoint}}/errors/10/comments/14
Content-Type: application/json
{{accessToken}}

{
    "content":"Hello c'est une modif",
    "user_id":5
}


#^ ------ deleteErrorComment
###
DELETE {{entryPoint}}/errors/10/comments/19
Content-Type: application/json
{{accessToken}}

{
    "user_id":5
}


#^ ------ fetchAllErrorCommentsByUser
###
GET {{entryPoint}}/users/10/error_comments
Content-Type: application/json
{{accessToken}}



#& -----------------------------------------------
#~ -------------------------------------- CATEGORY
#& -----------------------------------------------

#^ ------ createCategory
###
POST {{entryPoint}}/categories
Content-Type: application/json
{{accessToken}}

{
    "name": "Yumedo"
}


#^ ------ fetchAllCategories
###
GET {{entryPoint}}/categories
Content-Type: application/json

#^ ------ updateCategory

#^ ------ deleteCategory
###
DELETE {{entryPoint}}/categories/332
Content-Type: application/json
{{accessToken}}


#^ ------ fetchAllCategoriesByArticle
###
GET {{entryPoint}}/articles/2/categories
Content-Type: application/json


#^ ------ fetchAllCategoriesByErrorTicket
###
GET {{entryPoint}}/errors/10/categories
Content-Type: application/json



