@entryPoint = http://localhost:4100/api/v1

#* --------------------- USER

#& ---- All User
###
GET {{entryPoint}}/users
Content-Type: application/json

###
GET {{entryPoint}}/users/3
Content-Type: application/json

###
PUT {{entryPoint}}/users/3
Content-Type: application/json

{
    "username": "ADMIN",
    "is_active": false
}

###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "username": "Coucou_Heleneeeeeeeeee",
    "email": "Helene.Little89@yahoo.com",
    "password": "N6y$Ozddzt=1aa",
    "passwordConfirm": "N6y$Ozddzt=1aa"
}

###
POST {{entryPoint}}/signin
Content-Type: application/json

{
    "email": "Helene.Little89@yahoo.com",
    "password": "N6y$Ozddzt=1aa"
}

###
POST {{entryPoint}}/refreshToken
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSGVsZW5lLkxpdHRsZTg5QHlhaG9vLmNvbSIsImlhdCI6MTY1ODUwMTU0NCwiZXhwIjoxNjU4NTAyNzQ0fQ.UTzR18BqVm5FqWhUIwE-9hV44bQ4n2AQqNLwcO3zfbM

{
    "email": "Helene.Little89@yahoo.com"
}

###
PATCH {{entryPoint}}/users/2
Content-Type: application/json

{
    "username": "Coucou_Heleneeeeeeeeee",
    "email": "bridget.Hu@gmail.com",
    "password": "N6y$Ozddzt=1aa",
    "passwordConfirm": "N6y$Ozddzt=1aa",
    "profile_pic_url":"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg",
    "linkedin_url":"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/745.jpg",
    "id": 2
}

#* --------------------- ARTICLE

###
GET {{entryPoint}}/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZW1haWwiOiJIZWxlbmUuTGl0dGxlODlAeWFob28uY29tIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjU4NTAyNjY1LCJleHAiOjE2NTg1ODkwNjV9.L87n8PHMCXXrmWAeE3mhYazVE7Pec57B1NY6XCjxB0Q

###
POST {{entryPoint}}/articles
Content-Type: application/json

{
    "title": "test",
    "abstract": "test",
    "content": "test",
    "user_id":1,
    "status_id":1
}

###
GET {{entryPoint}}/articles/1
Content-Type: application/json


#* --------------------- ERROR
###
GET {{entryPoint}}/errors
Content-Type: application/json

###
GET {{entryPoint}}/errors/1
Content-Type: application/json


#* --------------------- ARTICLE COMMENT
###
GET {{entryPoint}}/articles/7/comments
Content-Type: application/json



#* --------------------- ERROR COMMENT
###
GET {{entryPoint}}/errors/3/comments
Content-Type: application/json


#* --------------------- CATEGORY
###
GET {{entryPoint}}/categories
Content-Type: application/json

###
GET {{entryPoint}}/categories/1
Content-Type: application/json

// Utilisateur
{
    "id": ,
    "username": "",
    "email": "",
    "password": "",
    "is_active": "",
    "title": "",
    "presentation": "",
    "profile_pic_url": "",
    "linkedin_url": "",
    "github_url": "",
    "instagram_url": "",
    "twitter_url": "",
    "portfolio_url": "",
    "role_id": "",
    "created_at": "",
    "updated_at": "",
}

// articles
{
    "id": ,
    "title": ,
    "abstract": ,
    "content": ,
    "user_id":,
    "status_id":,
    "created_at":,
    "updated_at":,
}

// Error Tickets
{
    "id": ,
    "error_snippet": ,
    "title": ,
    "abstract": ,
    "content":,
    "user_id":,
    "status_id":,
    "error_comment_id":,
    "created_at":,
    "updated_at"
}

// Article Comments
{
    "id": ,
    "content": ,
    "user_id": ,
    "article_id": ,
    "created_at": ,
    "updated_at":,
}

// Error ticket comments
{
    "id": ,
    "content": ,
    "user_id": ,
    "article_id": ,
    "error_id": ,
    "created_at":,
    "updated_at"
}

// category
{
    "id":,
    "name":,
    "logo_svg":,
}
